version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - '5173:5173'

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - '3018:3018'
